version: '3.9'

services:
  postgres:
    image: postgres
    env_file:
      - ./configs/production/.postgres.env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - 5434:5432
    deploy:
      restart_policy:
        condition: on-failure

  bot:
    image: antonioprojects/tracker_demo_bot:latest
    volumes:
      - .:/backend
    environment:
      PROD: 1
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
      - postgres

volumes:
  redis_data:
  postgres_data:
